//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.solutionsfit.calculator;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.solutionsfit.calculator.R.id;
import com.solutionsfit.calculator.R.layout;
import com.solutionsfit.calculator.R.string;

public final class Calculator_
    extends Calculator
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_calculator);
    }

    private void init_(Bundle savedInstanceState) {
        Resources resources_ = this.getResources();
        undefinedLabel = resources_.getString(string.undefined_label);
        totalLabel = resources_.getString(string.total_label);
        calculatorService = CalculatorBean_.getInstance_(this);
    }

    private void afterSetContentView_() {
        total = ((TextView) findViewById(id.total));
        secondNumber = ((EditText) findViewById(id.secondNumber));
        addButton = ((Button) findViewById(id.addButton));
        firstNumber = ((EditText) findViewById(id.firstNumber));
        {
            View view = findViewById(id.divideButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Calculator_.this.divideButton();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.addButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Calculator_.this.addButton();
                    }

                }
                );
            }
        }
        ((CalculatorBean_) calculatorService).afterSetContentView_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static Calculator_.IntentBuilder_ intent(Context context) {
        return new Calculator_.IntentBuilder_(context);
    }

    @Override
    public void showDivideResult(final Integer divideResult) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    Calculator_.super.showDivideResult(divideResult);
                } catch (RuntimeException e) {
                    Log.e("Calculator_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void handleDivide() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    Calculator_.super.handleDivide();
                } catch (RuntimeException e) {
                    Log.e("Calculator_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, Calculator_.class);
        }

        public Intent get() {
            return intent_;
        }

        public Calculator_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
