//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.solutionsfit.calculator;

import android.app.Activity;
import android.content.Context;
import android.content.res.Resources;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import com.solutionsfit.calculator.R.string;

public final class CalculatorBean_
    extends CalculatorBean
{

    private Context context_;
    private Handler handler_ = new Handler();

    private CalculatorBean_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        Resources resources_ = context_.getResources();
        divideByZeroMessage = resources_.getString(string.divide_by_zero_message);
        context = context_;
    }

    public static CalculatorBean_ getInstance_(Context context) {
        return new CalculatorBean_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

    @Override
    public void showMessage(final String message) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    CalculatorBean_.super.showMessage(message);
                } catch (RuntimeException e) {
                    Log.e("CalculatorBean_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

}
